server:
  port: 8080
  context-path: /

spring:
    mvc:
      view:
        prefix: /WEB-INF/views/
        suffix: .jsp

# 与mybatis整合
mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations:
  - classpath:mapper/*.xml

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: !!str true
  params: count=countSql
  
# 日志配置
debug: true

# 日志配置
logging:
  file: log/AhutOne.log
  level:
    # com.ahut包下所有class以DEBUG级别输出
    cn.angelbell.oa: DEBUG
    # root日志以WARN级别输出
    root: WARN
    org.springframework.boot.autoconfigure: ERROR
  config: classpath:logback-spring.xml